spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${RDS_URL}:${RDS_PORT}/${RDS_USERNAME}?createDatabaseIfNotExist=true
    username: ${RDS_DB_HOST}
    password: ${RDS_PASSWORD}

cloud:
  aws:
    credentials:
      access-key: ${ACCESS_KEY}
      secret-key: ${SECRET_KEY}
    region:
      static: ap-northeast-2
    s3:
      bucket: meetcha-kuit5
    stack:
      auto: false

server:
  forward-headers-strategy: native